apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:24.0.5
          ports:
          - name: http
            containerPort: 8080
          envFrom:
          - secretRef:
              name: keycloak-secret