from app.db.base_class import Base, BaseMixin
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import ForeignKey, Uuid


class Arena(Base, BaseMixin):
    # __tablename__ generated by Base

    question: Mapped[str] = mapped_column()
    user_id: Mapped[Uuid] = mapped_column(ForeignKey("user.id"))
    arena_model_responses: Mapped[list["ArenaModelResponse"]] = relationship(
        "ArenaModelResponse", back_populates="arena", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"Arena(id={self.id!r}"
