from app.db.base_class import Base, BaseMixin
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import Column, Integer, String, TIMESTAMP, Boolean, text, ForeignKey, Uuid


class ChatRoom(Base, BaseMixin):
    # __tablename__ generated by Base

    chats: Mapped[list["Chat"]] = relationship(
        "Chat", back_populates="chat_room", cascade="all, delete-orphan"
    )
    name: Mapped[str] = mapped_column()
    user_id: Mapped[Uuid] = mapped_column(ForeignKey("user.id"))

    def __repr__(self) -> str:
        return f"ChatRoom(id={self.id!r}, name={self.name!r}"
