apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  template:
    spec:
      containers:
      - name: postgres
        image: postgres:16
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-storage
          mountPath: /var/lib/postgresql/data
          subPath: lib
        - name: pg-storage
          mountPath: /var/log/postgresql
          subPath: log
        envFrom:
        - secretRef:
            name: postgres-secret
  volumeClaimTemplates:
  - metadata:
      name: pg-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
